export enum UaaEvent {
  LOAD_IDENTITY_START,
  LOAD_IDENTITY_SUCCESS,
  LOAD_IDENTITY_ERROR,

  LOGIN_REQUIRED,
  LOGIN_PROVIDED,

  LOGIN_START,
  LOGIN_SUCCESS,
  LOGIN_FAILED,

  LOGOUT_START,
  LOGOUT_SUCCESS,
  LOGOUT_FAILED,

  LOGIN_DIALOG_BEFORE_OPEN,
  LOGIN_DIALOG_OPENED,
  LOGIN_DIALOG_BEFORE_CLOSED,
  LOGIN_DIALOG_CLOSED,

  REGISTRATION_REQUESTED,

  REQUEST_BUFFERED
}
